# Generated by Django 5.0.3 on 2024-03-24 19:33

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_refreshtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "videoFile",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="videoFile"
                    ),
                ),
                (
                    "thumbnailFile",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="thumbnail"
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                (
                    "description",
                    models.CharField(max_length=50, verbose_name="description"),
                ),
                (
                    "duration",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="duration"
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
            },
        ),
    ]
